// trainerData.ts
import { Trainer } from './types';

export const TRAINER_DATA: Trainer = {
  name: 'Ramon',
  level: 1,
  ac: 10,
  maxHp: 8,
  maxHitDice: 1,
  biography: {
    species: 'Human',
    gender: '',
    age: '',
    homeRegion: 'e.g. Sinnoh',
    background: 'e.g. Entertainer',
    avatarUrl: ''
  },
  attributes: {
    STR: 10,
    DEX: 10,
    CON: 10,
    INT: 10,
    WIS: 10,
    CHA: 10,
  },
  savingThrows: [
    { name: 'Strength', proficient: false },
    { name: 'Dexterity', proficient: false },
    { name: 'Constitution', proficient: false },
    { name: 'Intelligence', proficient: false },
    { name: 'Wisdom', proficient: false },
    { name: 'Charisma', proficient: true },
  ],
  proficiencies: [
    { name: 'Atletismo', attribute: 'STR', level: 0 },
    { name: 'Luta', attribute: 'STR', level: 0 },
    { name: 'Acrobacia', attribute: 'DEX', level: 0 },
    { name: 'Furtividade', attribute: 'DEX', level: 0 },
    { name: 'Pilotagem', attribute: 'DEX', level: 0 },
    { name: 'Pontaria', attribute: 'DEX', level: 0 },
    { name: 'Reflexos', attribute: 'DEX', level: 0 },
    { name: 'Fortitude', attribute: 'CON', level: 0 },
    { name: 'Atualidades', attribute: 'INT', level: 0 },
    { name: 'Ciências', attribute: 'INT', level: 0 },
    { name: 'Investigação', attribute: 'INT', level: 0 },
    { name: 'Medicina', attribute: 'WIS', level: 0 },
    { name: 'Ocultismo', attribute: 'INT', level: 0 },
    { name: 'Profissão', attribute: 'INT', level: 0 },
    { name: 'Tecnologia', attribute: 'INT', level: 0 },
    { name: 'Adestramento', attribute: 'WIS', level: 1 },
    { name: 'Artes', attribute: 'CHA', level: 0 },
    { name: 'Diplomacia', attribute: 'CHA', level: 0 },
    { name: 'Enganação', attribute: 'CHA', level: 0 },
    { name: 'Intimidação', attribute: 'CHA', level: 0 },
    { name: 'Intuição', attribute: 'WIS', level: 0 },
    { name: 'Percepção', attribute: 'WIS', level: 0 },
    { name: 'Sobrevivência', attribute: 'WIS', level: 0 },
    { name: 'Vontade', attribute: 'WIS', level: 0 },
  ],
  specializations: [
    { name: 'Poké Fan', type: 'normal', value: 0, color: '#a8a878' },
    { name: 'Black Belt', type: 'fighting', value: 0, color: '#c03028' },
    { name: 'Bird Keeper', type: 'flying', value: 0, color: '#a890f0' },
    { name: 'Punk', type: 'poison', value: 0, color: '#a040a0' },
    { name: 'Camper', type: 'ground', value: 0, color: '#e0c068' },
    { name: 'Hiker', type: 'rock', value: 0, color: '#b8a038' },
    { name: 'Bug Maniac', type: 'bug', value: 0, color: '#a8b820' },
    { name: 'Mystic', type: 'ghost', value: 0, color: '#705898' },
    { name: 'Worker', type: 'steel', value: 0, color: '#b8b8d0' },
    { name: 'Kindler', type: 'fire', value: 0, color: '#f08030' },
    { name: 'Swimmer', type: 'water', value: 0, color: '#6890f0' },
    { name: 'Gardener', type: 'grass', value: 0, color: '#78c850' },
    { name: 'Engineer', type: 'electric', value: 0, color: '#f8d030' },
    { name: 'Psychic', type: 'psychic', value: 0, color: '#f85888' },
    { name: 'Skier', type: 'ice', value: 0, color: '#98d8d8' },
    { name: 'Dragon Tamer', type: 'dragon', value: 0, color: '#7038f8' },
    { name: 'Delinquent', type: 'dark', value: 0, color: '#705848' },
    { name: 'Actor', type: 'fairy', value: 0, color: '#ee99ac' },
  ],
  trainerPath: '',
  feats: [
    { name: 'Chef', notes: '' },
  ],
  notes: '',
  inventory: {
    money: 2500, // Updated from 1500 to reflect 1000 + 100 * 4d4 (using average roll of 10 for d4s)
    items: [
      { id: 'poke-ball', quantity: 5 },
      { id: 'potion', quantity: 1 },
    ],
  },
  about: 'Rocha',
};